# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'offers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(691, 597)
        self.back_button = QtWidgets.QPushButton(Dialog)
        self.back_button.setGeometry(QtCore.QRect(60, 510, 75, 23))
        self.back_button.setObjectName("back_button")
        self.offers_data = QtWidgets.QTableWidget(Dialog)
        self.offers_data.setGeometry(QtCore.QRect(60, 40, 521, 201))
        self.offers_data.setObjectName("offers_data")
        self.offers_data.setColumnCount(4)
        self.offers_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.offers_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.offers_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.offers_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.offers_data.setHorizontalHeaderItem(3, item)
        self.send_off_btn = QtWidgets.QPushButton(Dialog)
        self.send_off_btn.setGeometry(QtCore.QRect(450, 420, 141, 41))
        self.send_off_btn.setObjectName("send_off_btn")
        self.id_offer = QtWidgets.QTextEdit(Dialog)
        self.id_offer.setGeometry(QtCore.QRect(450, 360, 141, 41))
        self.id_offer.setObjectName("id_offer")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.back_button.setText(_translate("Dialog", "back"))
        item = self.offers_data.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Название"))
        item = self.offers_data.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ID"))
        item = self.offers_data.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Адрес доставки"))
        item = self.offers_data.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "ID заказа"))
        self.send_off_btn.setText(_translate("Dialog", "Отправить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
